### ISSUE TITLE
algunos links hacen el el m3u salga vacio.

### ISSUE THREAD

**Issue by zeknewbe** [wetdreams69/iptv_argentina#1]
Al cargar algunos canales y correr el generator sale el m3u en blanco ... tenés idea por que?

**Comment by wetdreams69** [comment]
Puede ser por varias razones:
URL Normal: La pagina no responde.
Twitch: Canal cerrado por copyright o el canal no esta transmitiendo.
Youtube: Canal con Geo-Bloqueo.

Igual te recomiendo copiar el proyecto de nuevo y correrlo con tu channel_info.txt. A partir de la ultima version se genera el archivo log.txt. Si en ese archivo no sale ningun stream directamente no pudo obtener el link.

**Comment by zeknewbe** [comment]
genial gracias!
